[tool.black]
line-length = 88        # Default line length
target-version = ['py310']  # Your Python version
include = '\.pyi?$'     # Include Python files
extend-exclude = '''
# Exclude files or directories:
/(
    \.git
  | \.venv
  | venv
)/
'''

[tool.isort]
profile = "black"       # Make isort compatible with black
multi_line_output = 3   # Vertical Hanging Indent
line_length = 88       # Match black's line length
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true
ensure_newline_before_comments = true
skip = [".git", ".venv","venv"]
